server:
  port: 0

spring:
  application:
    name: user-service
  h2:
    console:
      enable: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
  #zipkin
  zipkin:
    base-url: http://127.0.0.1:9411
    enable : true
  sleuth:
    sampler:
      probability: 1.0


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message: Welcome to Simple E-Commerce.

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, info, busrefresh, metrics, prometheus

#FeignClient 로그
logging:
  level:
    com.example.userservice.client: DEBUG